[tools]
java = "temurin-21"
just = "1.58.0"
rust = "1.97.1"
zig = "0.15.2"

[env]
ZIG_LOCAL_CACHE_DIR = "{{config_root}}/.local/cache/zig"
ZIG_GLOBAL_CACHE_DIR = "{{config_root}}/.local/cache/zig-global"

[settings]
lockfile = true
